Repository vuejs/jp.vuejs.org, pull requests merged in 2019-01, with the labels that each got.

#1372 fixed-typo
  src/v2/guide/components-edge-cases.md
Labels: PR: reviewed-approved

#1374 Fix mixin data merging documentation
  src/v2/guide/mixins.md
Labels: PR: reviewed-approved

#1375 Adding pathways to free Video content
  src/v2/guide/index.md
  src/v2/guide/installation.md
  src/v2/guide/reactivity.md
  src/v2/guide/state-management.md
  themes/vue/layout/index.ejs
  themes/vue/source/css/_modal.styl
  themes/vue/source/css/_vue-mastery.styl
  themes/vue/source/css/page.styl
Labels: PR: reviewed-approved

#1382 chore: new contributor
  themes/vue/layout/partials/contribution_contents.ejs
Labels: PR: reviewed-approved

#1271 Translate weekly news letter form
  themes/vue/layout/index.ejs
Labels: PR: unreviewed

#1383 Update trim description in forms.md
  src/v2/guide/forms.md
Labels: PR: unreviewed

#1384 "Default Slot content text was unclear" の翻訳
  src/v2/guide/components-slots.md
Labels: PR: reviewed-approved

#1390 vuetronのリンク変更
  src/v2/cookbook/debugging-in-vscode.md
Labels: PR: unreviewed

#1401 Translate en doc updates
  src/v2/cookbook/dockerize-vuejs-app.md
  src/v2/cookbook/unit-testing-vue-components.md
  src/v2/guide/render-function.md
Labels: PR: reviewed-approved

#1414 Update invalid live demo link
  src/v2/examples/hackernews.md
Labels: PR: unreviewed

#1431 doc: Remove Vuetron
  src/v2/cookbook/debugging-in-vscode.md
Labels: PR: reviewed-approved, PR: unreviewed

#1435 Translate: Add comments about $watch behavior with a function
  src/v2/api/index.md
Labels: PR: reviewed-approved

#1442 Translate misc updates
  src/v2/guide/components-slots.md
  themes/vue/layout/partials/ecosystem_dropdown.ejs
Labels: PR: unreviewed
