Repository vuejs/jp.vuejs.org, pull requests merged in 2020-05, with the labels that each got.

#2109 [Doc]: Add deployed on Netlify link #2093
  themes/vue/layout/page.ejs
Labels: PR: partially-approved

#2115 Translate 2106, 2108
  src/v2/guide/state-management.md
  themes/vue/layout/partials/language_dropdown.ejs
Labels: PR: partially-approved

#2116 [Doc]: Update packaging-sfc-for-npm.md #2111
  src/v2/cookbook/packaging-sfc-for-npm.md
Labels: PR: partially-approved

#2130 Modify migration.vuex
  src/v2/guide/migration-vuex.md
Labels: PR: reviewed-approved

#2133 Added translation of "Annotating Props" #2103
  src/v2/guide/typescript.md
Labels: PR: reviewed-approved

#2135 [Doc]: add Capacitor
  src/v2/guide/ssr.md
Labels: PR: reviewed-approved

#2138 fix: forms.html, remove the wrapper div
  src/v2/guide/forms.md
Labels: PR: reviewed-approved

#2139 Re: fix: forms.html, remove the wrapper div
  src/v2/guide/forms.md
Labels: PR: unreviewed

#2136 fix italic of 2 letters
  src/v2/cookbook/index.md
  src/v2/guide/components-edge-cases.md
  src/v2/style-guide/index.md
Labels: PR: reviewed-approved

#2141 [Doc]: [nitpicking] import() is not a function
  src/v2/guide/components-dynamic-async.md
Labels: PR: reviewed-approved

#2121 fix: update more unit test code examples with Vue Test Utils
  src/v2/guide/unit-testing.md
Labels: PR: partially-approved
